'use strict';

const CATEGORIES = [
  { key: 'hosting',        label: 'Hosting',        color: '#4f9cf9' },
  { key: 'backend',        label: 'Backend',        color: '#a78bfa' },
  { key: 'infrastructure', label: 'Infrastructure', color: '#f97316' },
  { key: 'ai',             label: 'AI / LLM',       color: '#00d4aa' },
  { key: 'mobile',         label: 'Mobile',         color: '#fbbf24' },
  { key: 'devtools',       label: 'Dev Tools',      color: '#f472b6' },
  { key: 'network',        label: 'Network',        color: '#38bdf8' },
  { key: 'other',          label: 'Other',          color: '#94a3b8' },
];

const BILLING_TYPES = [
  { key: 'fixed_monthly',  label: 'Fixed Monthly' },
  { key: 'fixed_annual',   label: 'Fixed Annual (amortized)' },
  { key: 'per_user',       label: 'Per User / MAU' },
  { key: 'usage_per_user', label: 'Usage per User' },
  { key: 'one_time',       label: 'One-Time (amortized)' },
  { key: 'per_seat',       label: 'Per Dev Seat' },
];

// Service catalog — presets users can instantiate as cost entries.
// usagePerUser + unitCost → monthly = usagePerUser × unitCost × MAU
// unitLabel describes the unit of usagePerUser (e.g. "tokens/month per user")
const CATALOG = [

  // ── HOSTING ──────────────────────────────────────────────────
  {
    key: 'firebase_hosting_free',
    name: 'Firebase Hosting (Spark Free)',
    category: 'hosting', billingType: 'fixed_monthly',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '1 GB storage, 10 GB/month transfer',
    url: 'https://firebase.google.com/pricing',
  },
  {
    key: 'firebase_hosting_blaze',
    name: 'Firebase Hosting — Bandwidth (Blaze)',
    category: 'hosting', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0.05, unitCost: 0.12, unitLabel: 'GB/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.12/GB bandwidth after 10 GB/month free',
    url: 'https://firebase.google.com/pricing',
  },
  {
    key: 'vercel_free',
    name: 'Vercel Free',
    category: 'hosting', billingType: 'fixed_monthly',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: 'Hobby plan — 100 GB bandwidth/month',
    url: 'https://vercel.com/pricing',
  },
  {
    key: 'vercel_pro',
    name: 'Vercel Pro',
    category: 'hosting', billingType: 'fixed_monthly',
    baseAmount: 20, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$20/month — 1 TB bandwidth, preview deploys',
    url: 'https://vercel.com/pricing',
  },
  {
    key: 'vercel_team',
    name: 'Vercel Team',
    category: 'hosting', billingType: 'per_seat',
    baseAmount: 20, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$20/seat/month',
    url: 'https://vercel.com/pricing',
  },
  {
    key: 'netlify_free',
    name: 'Netlify Free',
    category: 'hosting', billingType: 'fixed_monthly',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '100 GB bandwidth, 300 build minutes/month',
    url: 'https://www.netlify.com/pricing',
  },
  {
    key: 'netlify_pro',
    name: 'Netlify Pro',
    category: 'hosting', billingType: 'fixed_monthly',
    baseAmount: 19, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$19/month — 1 TB bandwidth, 25K form submissions',
    url: 'https://www.netlify.com/pricing',
  },
  {
    key: 'netlify_business',
    name: 'Netlify Business',
    category: 'hosting', billingType: 'fixed_monthly',
    baseAmount: 99, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$99/month — 2 TB bandwidth, SAML SSO',
    url: 'https://www.netlify.com/pricing',
  },
  {
    key: 'cloudflare_pages_free',
    name: 'Cloudflare Pages Free',
    category: 'hosting', billingType: 'fixed_monthly',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: 'Unlimited bandwidth, 500 builds/month',
    url: 'https://pages.cloudflare.com',
  },
  {
    key: 'cloudflare_pro',
    name: 'Cloudflare Pro',
    category: 'hosting', billingType: 'fixed_monthly',
    baseAmount: 20, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$20/month — WAF, DDoS protection, analytics',
    url: 'https://www.cloudflare.com/plans',
  },
  {
    key: 'aws_s3_cloudfront',
    name: 'AWS S3 + CloudFront',
    category: 'hosting', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0.005, unitCost: 0.085, unitLabel: 'GB/month per user', seats: 1, amortizeMonths: 12,
    description: '~$0.085/GB transfer, $0.023/GB storage',
    url: 'https://aws.amazon.com/cloudfront/pricing',
  },
  {
    key: 'render_free',
    name: 'Render Static Sites (Free)',
    category: 'hosting', billingType: 'fixed_monthly',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: 'Free static sites, 100 GB bandwidth',
    url: 'https://render.com/pricing',
  },
  {
    key: 'render_individual',
    name: 'Render Web Service (Individual)',
    category: 'hosting', billingType: 'fixed_monthly',
    baseAmount: 7, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$7/month web service',
    url: 'https://render.com/pricing',
  },

  // ── BACKEND ──────────────────────────────────────────────────
  {
    key: 'supabase_free',
    name: 'Supabase Free',
    category: 'backend', billingType: 'fixed_monthly',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '500 MB database, 1 GB storage, 2 projects',
    url: 'https://supabase.com/pricing',
  },
  {
    key: 'supabase_pro',
    name: 'Supabase Pro',
    category: 'backend', billingType: 'fixed_monthly',
    baseAmount: 25, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$25/month — 8 GB database, 100 GB storage',
    url: 'https://supabase.com/pricing',
  },
  {
    key: 'supabase_team',
    name: 'Supabase Team',
    category: 'backend', billingType: 'fixed_monthly',
    baseAmount: 599, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$599/month — SOC2, priority support',
    url: 'https://supabase.com/pricing',
  },
  {
    key: 'firebase_firestore',
    name: 'Firebase Firestore (Blaze) — Reads',
    category: 'backend', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 1000, unitCost: 0.0000006, unitLabel: 'reads/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.06/100K reads after 50K/day free',
    url: 'https://firebase.google.com/pricing',
  },
  {
    key: 'firebase_firestore_writes',
    name: 'Firebase Firestore (Blaze) — Writes',
    category: 'backend', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 200, unitCost: 0.0000018, unitLabel: 'writes/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.18/100K writes after 20K/day free',
    url: 'https://firebase.google.com/pricing',
  },
  {
    key: 'firebase_auth',
    name: 'Firebase Auth (phone/SMS)',
    category: 'backend', billingType: 'per_user',
    baseAmount: 0, perUserAmount: 0.0055, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$0.0055/MAU for phone auth after 10K free/month',
    url: 'https://firebase.google.com/pricing',
  },
  {
    key: 'firebase_functions',
    name: 'Firebase Cloud Functions',
    category: 'backend', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 10, unitCost: 0.0000004, unitLabel: 'invocations/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.40/1M invocations after 2M free/month',
    url: 'https://firebase.google.com/pricing',
  },
  {
    key: 'planetscale_scaler',
    name: 'PlanetScale Scaler',
    category: 'backend', billingType: 'fixed_monthly',
    baseAmount: 39, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$39/month — 10 GB storage, 100M row reads',
    url: 'https://planetscale.com/pricing',
  },
  {
    key: 'neon_launch',
    name: 'Neon Launch',
    category: 'backend', billingType: 'fixed_monthly',
    baseAmount: 19, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$19/month — 10 GB storage, serverless Postgres',
    url: 'https://neon.tech/pricing',
  },
  {
    key: 'neon_scale',
    name: 'Neon Scale',
    category: 'backend', billingType: 'fixed_monthly',
    baseAmount: 69, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$69/month — 50 GB storage, autoscaling',
    url: 'https://neon.tech/pricing',
  },
  {
    key: 'railway_hobby',
    name: 'Railway Hobby',
    category: 'backend', billingType: 'fixed_monthly',
    baseAmount: 5, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$5/month base credit',
    url: 'https://railway.app/pricing',
  },
  {
    key: 'railway_pro',
    name: 'Railway Pro',
    category: 'backend', billingType: 'fixed_monthly',
    baseAmount: 20, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$20/month + usage-based compute',
    url: 'https://railway.app/pricing',
  },

  // ── AI / LLM ─────────────────────────────────────────────────
  // Blended input/output token cost: (input_price + output_price) / 2
  {
    key: 'openai_gpt4o',
    name: 'OpenAI GPT-4o',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 10000, unitCost: 0.000010, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$5/1M input · $15/1M output tokens',
    url: 'https://openai.com/pricing',
  },
  {
    key: 'openai_gpt4o_mini',
    name: 'OpenAI GPT-4o mini',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 10000, unitCost: 0.000000375, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.15/1M input · $0.60/1M output tokens',
    url: 'https://openai.com/pricing',
  },
  {
    key: 'openai_gpt4_turbo',
    name: 'OpenAI GPT-4 Turbo',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 5000, unitCost: 0.000020, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$10/1M input · $30/1M output tokens',
    url: 'https://openai.com/pricing',
  },
  {
    key: 'openai_gpt35_turbo',
    name: 'OpenAI GPT-3.5 Turbo',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 20000, unitCost: 0.000001, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.50/1M input · $1.50/1M output tokens',
    url: 'https://openai.com/pricing',
  },
  {
    key: 'openai_o1',
    name: 'OpenAI o1',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 2000, unitCost: 0.0000225, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$15/1M input · $60/1M output (reasoning) tokens',
    url: 'https://openai.com/pricing',
  },
  {
    key: 'anthropic_claude_opus',
    name: 'Anthropic Claude Opus 4',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 5000, unitCost: 0.000045, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$15/1M input · $75/1M output tokens',
    url: 'https://www.anthropic.com/pricing',
  },
  {
    key: 'anthropic_claude_sonnet',
    name: 'Anthropic Claude Sonnet 4.6',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 10000, unitCost: 0.000009, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$3/1M input · $15/1M output tokens',
    url: 'https://www.anthropic.com/pricing',
  },
  {
    key: 'anthropic_claude_haiku',
    name: 'Anthropic Claude Haiku 4.5',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 20000, unitCost: 0.00000075, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.25/1M input · $1.25/1M output tokens',
    url: 'https://www.anthropic.com/pricing',
  },
  {
    key: 'gemini_15_pro',
    name: 'Google Gemini 1.5 Pro',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 10000, unitCost: 0.000007, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$3.50/1M input · $10.50/1M output tokens',
    url: 'https://ai.google.dev/pricing',
  },
  {
    key: 'gemini_15_flash',
    name: 'Google Gemini 1.5 Flash',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 20000, unitCost: 0.0000001875, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.075/1M input · $0.30/1M output tokens',
    url: 'https://ai.google.dev/pricing',
  },
  {
    key: 'gemini_20_flash',
    name: 'Google Gemini 2.0 Flash',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 20000, unitCost: 0.00000025, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.10/1M input · $0.40/1M output tokens',
    url: 'https://ai.google.dev/pricing',
  },
  {
    key: 'mistral_large',
    name: 'Mistral Large',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 10000, unitCost: 0.000004, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$2/1M input · $6/1M output tokens',
    url: 'https://mistral.ai/technology/#pricing',
  },
  {
    key: 'mistral_small',
    name: 'Mistral Small',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 20000, unitCost: 0.0000004, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.20/1M input · $0.60/1M output tokens',
    url: 'https://mistral.ai/technology/#pricing',
  },
  {
    key: 'mistral_codestral',
    name: 'Mistral Codestral',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 5000, unitCost: 0.0000005, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.20/1M input · $0.60/1M output tokens (code)',
    url: 'https://mistral.ai/technology/#pricing',
  },
  {
    key: 'groq_llama3_70b',
    name: 'Groq Llama 3.1 70B',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 20000, unitCost: 0.00000069, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.59/1M input · $0.79/1M output tokens',
    url: 'https://groq.com/pricing',
  },
  {
    key: 'groq_llama3_8b',
    name: 'Groq Llama 3.1 8B',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 20000, unitCost: 0.00000012, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.05/1M input · $0.08/1M output tokens',
    url: 'https://groq.com/pricing',
  },
  {
    key: 'cohere_command_r_plus',
    name: 'Cohere Command R+',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 10000, unitCost: 0.000009, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$3/1M input · $15/1M output tokens',
    url: 'https://cohere.com/pricing',
  },
  {
    key: 'cohere_command_r',
    name: 'Cohere Command R',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 10000, unitCost: 0.00000075, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.15/1M input · $0.60/1M output tokens',
    url: 'https://cohere.com/pricing',
  },
  {
    key: 'xai_grok',
    name: 'xAI Grok',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 10000, unitCost: 0.0000075, unitLabel: 'tokens/month per user', seats: 1, amortizeMonths: 12,
    description: '$5/1M input · $15/1M output tokens',
    url: 'https://x.ai/api',
  },
  {
    key: 'perplexity_sonar',
    name: 'Perplexity Sonar Pro',
    category: 'ai', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 100, unitCost: 0.005, unitLabel: 'requests/month per user', seats: 1, amortizeMonths: 12,
    description: '$5/1K requests (online search + reasoning)',
    url: 'https://docs.perplexity.ai/docs/pricing',
  },

  // ── MOBILE ───────────────────────────────────────────────────
  {
    key: 'apple_app_store',
    name: 'Apple App Store (Developer)',
    category: 'mobile', billingType: 'fixed_annual',
    baseAmount: 99, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$99/year developer account (→ $8.25/month)',
    url: 'https://developer.apple.com/programs',
  },
  {
    key: 'google_play_store',
    name: 'Google Play Store (Developer)',
    category: 'mobile', billingType: 'one_time',
    baseAmount: 25, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 36,
    description: '$25 one-time registration (amortized over 36 months)',
    url: 'https://play.google.com/console',
  },
  {
    key: 'revenuecat_starter',
    name: 'RevenueCat Starter',
    category: 'mobile', billingType: 'fixed_monthly',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: 'Free up to $2,500 MTR',
    url: 'https://www.revenuecat.com/pricing',
  },
  {
    key: 'expo_eas',
    name: 'Expo EAS Build',
    category: 'mobile', billingType: 'fixed_monthly',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: 'Free tier — 30 builds/month; Production $99/month',
    url: 'https://expo.dev/pricing',
  },

  // ── DEV TOOLS ────────────────────────────────────────────────
  {
    key: 'claude_code',
    name: 'Claude Code',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 20, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$20/seat/month (or $200/year)',
    url: 'https://claude.ai',
  },
  {
    key: 'cursor',
    name: 'Cursor',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 20, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$20/seat/month (or $192/year)',
    url: 'https://cursor.com/pricing',
  },
  {
    key: 'github_copilot_individual',
    name: 'GitHub Copilot Individual',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 10, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$10/seat/month (or $100/year)',
    url: 'https://github.com/features/copilot',
  },
  {
    key: 'github_copilot_business',
    name: 'GitHub Copilot Business',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 19, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$19/seat/month — org-wide policies',
    url: 'https://github.com/features/copilot',
  },
  {
    key: 'jetbrains_ai',
    name: 'JetBrains AI Assistant',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 10, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$10/seat/month (or $100/year)',
    url: 'https://www.jetbrains.com/ai',
  },
  {
    key: 'linear',
    name: 'Linear',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 8, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$8/seat/month — project management',
    url: 'https://linear.app/pricing',
  },
  {
    key: 'figma_professional',
    name: 'Figma Professional',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 15, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$15/seat/month — design tool',
    url: 'https://www.figma.com/pricing',
  },
  {
    key: 'notion_teams',
    name: 'Notion Teams',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 16, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$16/seat/month',
    url: 'https://www.notion.so/pricing',
  },
  {
    key: 'slack_pro',
    name: 'Slack Pro',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 7.25, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$7.25/seat/month',
    url: 'https://slack.com/pricing',
  },
  {
    key: 'github_teams',
    name: 'GitHub Teams',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 4, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$4/seat/month',
    url: 'https://github.com/pricing',
  },
  {
    key: 'datadog_pro',
    name: 'Datadog Pro',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 15, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$15/seat/month — APM, logs, dashboards',
    url: 'https://www.datadoghq.com/pricing',
  },
  {
    key: 'sentry_team',
    name: 'Sentry Team',
    category: 'devtools', billingType: 'fixed_monthly',
    baseAmount: 26, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$26/month — error monitoring, 50K errors/month',
    url: 'https://sentry.io/pricing',
  },
  {
    key: 'postman_basic',
    name: 'Postman Basic',
    category: 'devtools', billingType: 'per_seat',
    baseAmount: 14, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$14/seat/month — API development',
    url: 'https://www.postman.com/pricing',
  },

  // ── NETWORK ──────────────────────────────────────────────────
  {
    key: 'cdn_bandwidth_generic',
    name: 'CDN Bandwidth (generic)',
    category: 'network', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0.05, unitCost: 0.08, unitLabel: 'GB/month per user', seats: 1, amortizeMonths: 12,
    description: '~$0.08/GB CDN egress (average across providers)',
    url: '',
  },
  {
    key: 'firebase_storage_bandwidth',
    name: 'Firebase Storage Download',
    category: 'network', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0.1, unitCost: 0.12, unitLabel: 'GB/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.12/GB after 1 GB/day free',
    url: 'https://firebase.google.com/pricing',
  },
  {
    key: 'supabase_storage_bandwidth',
    name: 'Supabase Storage Bandwidth',
    category: 'network', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0.05, unitCost: 0.09, unitLabel: 'GB/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.09/GB after 5 GB/month free (Pro plan)',
    url: 'https://supabase.com/pricing',
  },
  {
    key: 'aws_data_transfer',
    name: 'AWS Data Transfer Out',
    category: 'network', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0.05, unitCost: 0.09, unitLabel: 'GB/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.09/GB out to internet (first 10 TB/month)',
    url: 'https://aws.amazon.com/ec2/pricing/on-demand',
  },
  {
    key: 'twilio_sms',
    name: 'Twilio SMS',
    category: 'network', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 1, unitCost: 0.0079, unitLabel: 'SMS/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.0079/SMS sent (US domestic)',
    url: 'https://www.twilio.com/en-us/sms/pricing',
  },
  {
    key: 'sendgrid_essentials',
    name: 'SendGrid Essentials',
    category: 'network', billingType: 'fixed_monthly',
    baseAmount: 19.95, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$19.95/month — 50K emails/month',
    url: 'https://sendgrid.com/pricing',
  },
  {
    key: 'resend',
    name: 'Resend',
    category: 'network', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 2, unitCost: 0.0004, unitLabel: 'emails/month per user', seats: 1, amortizeMonths: 12,
    description: '$0.40/1K emails after 3K free/month',
    url: 'https://resend.com/pricing',
  },

  // ── INFRASTRUCTURE (VPS / Servers) ──────────────────────────
  {
    key: 'hetzner_cx22',
    name: 'Hetzner CX22 (2 vCPU / 4 GB)',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 5.20, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '~€4.85/mo — shared AMD, 2 vCPU, 4 GB RAM, 40 GB SSD',
    url: 'https://www.hetzner.com/cloud',
  },
  {
    key: 'hetzner_cx32',
    name: 'Hetzner CX32 (4 vCPU / 8 GB)',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 8.90, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '~€8.22/mo — shared AMD, 4 vCPU, 8 GB RAM, 80 GB SSD',
    url: 'https://www.hetzner.com/cloud',
  },
  {
    key: 'hetzner_cx42',
    name: 'Hetzner CX42 (8 vCPU / 16 GB)',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 17.20, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '~€15.90/mo — shared AMD, 8 vCPU, 16 GB RAM, 160 GB SSD',
    url: 'https://www.hetzner.com/cloud',
  },
  {
    key: 'hetzner_cx52',
    name: 'Hetzner CX52 (16 vCPU / 32 GB)',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 32.90, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '~€30.43/mo — shared AMD, 16 vCPU, 32 GB RAM, 320 GB SSD',
    url: 'https://www.hetzner.com/cloud',
  },
  {
    key: 'hetzner_cpx21',
    name: 'Hetzner CPX21 (3 vCPU dedicated / 4 GB)',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 11.65, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '~€10.76/mo — dedicated AMD, 3 vCPU, 4 GB RAM, 80 GB NVMe',
    url: 'https://www.hetzner.com/cloud',
  },
  {
    key: 'hetzner_cpx31',
    name: 'Hetzner CPX31 (4 vCPU dedicated / 8 GB)',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 20.70, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '~€19.13/mo — dedicated AMD, 4 vCPU, 8 GB RAM, 160 GB NVMe',
    url: 'https://www.hetzner.com/cloud',
  },
  {
    key: 'hetzner_ccx13',
    name: 'Hetzner CCX13 (2 vCPU dedicated Intel / 8 GB)',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 16.10, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '~€14.90/mo — dedicated Intel, 2 vCPU, 8 GB RAM, 80 GB NVMe',
    url: 'https://www.hetzner.com/cloud',
  },
  {
    key: 'hetzner_load_balancer',
    name: 'Hetzner Load Balancer LB11',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 7.65, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '~€7.09/mo — 25 targets, 20 TB traffic included',
    url: 'https://www.hetzner.com/cloud/load-balancer',
  },
  {
    key: 'hetzner_volume',
    name: 'Hetzner Block Storage Volume',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 5.60, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '~€0.0540/GB/mo — example: 100 GB ≈ €5.40/mo',
    url: 'https://www.hetzner.com/storage/storage-volumes',
  },
  {
    key: 'hetzner_object_storage',
    name: 'Hetzner Object Storage',
    category: 'infrastructure', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0.01, unitCost: 0.027, unitLabel: 'GB/month per user', seats: 1, amortizeMonths: 12,
    description: '~€0.025/GB/mo object storage (S3-compatible)',
    url: 'https://www.hetzner.com/storage/object-storage',
  },
  {
    key: 'hetzner_traffic',
    name: 'Hetzner Outbound Traffic (overage)',
    category: 'infrastructure', billingType: 'usage_per_user',
    baseAmount: 0, perUserAmount: 0, usagePerUser: 0.05, unitCost: 0.013, unitLabel: 'GB/month per user', seats: 1, amortizeMonths: 12,
    description: '€0.012/GB outbound after included traffic; inbound is free',
    url: 'https://www.hetzner.com/cloud',
  },
  // Other popular VPS providers for comparison
  {
    key: 'digitalocean_basic',
    name: 'DigitalOcean Droplet (Basic 2 GB)',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 12, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$12/mo — 1 vCPU, 2 GB RAM, 50 GB SSD, 2 TB transfer',
    url: 'https://www.digitalocean.com/pricing/droplets',
  },
  {
    key: 'fly_io',
    name: 'Fly.io (shared-cpu-2x, 512MB)',
    category: 'infrastructure', billingType: 'fixed_monthly',
    baseAmount: 3.19, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
    description: '$3.19/mo — shared CPU, 512 MB RAM (billed per second)',
    url: 'https://fly.io/docs/about/pricing',
  },
];

// Build lookup maps
const CATALOG_BY_KEY = Object.fromEntries(CATALOG.map(c => [c.key, c]));
const CATALOG_BY_CATEGORY = CATALOG.reduce((acc, item) => {
  (acc[item.category] = acc[item.category] || []).push(item);
  return acc;
}, {});

function getCategoryMeta(key) {
  return CATEGORIES.find(c => c.key === key) || CATEGORIES[CATEGORIES.length - 1];
}

// Pre-built demo stack: Firebase + Supabase + OpenAI + Hetzner + Mobile
// Per-user cost breakdown at 1 000 MAU with this stack:
//   Fixed  : Supabase Pro $25 + OpenAI API budget $2 + Hetzner CX32 $8.90
//            + App Store amortized $8.25 + Play Store amortized $0.69 = $44.84
//   Variable per user (1K MAU):
//     Supabase egress   : 0.05 GB × $0.09 × 1K = $4.50
//     Firebase reads    : 500   × $0.0000006 × 1K = $0.30
//     Firebase functions: 10    × $0.0000004 × 1K = $0.004
//   Total ~$49.60 → ≈ $0.050/user/month at 1 000 MAU
const SAMPLE_STACK = {
  name: 'Firebase + Supabase + Hetzner Stack',
  currency: 'USD',
  monthlyActiveUsers: 1000,
  developers: 3,
  costs: [
    // ── Frontend hosting ──
    {
      id: 'demo-1', name: 'Firebase Hosting (Spark Free)', serviceKey: 'firebase_hosting_free',
      category: 'hosting', billingType: 'fixed_monthly',
      baseAmount: 0, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
      notes: 'Free tier — serves the Vue.js frontend', enabled: true,
    },
    // ── Backend / Database ──
    {
      id: 'demo-2', name: 'Supabase Pro', serviceKey: 'supabase_pro',
      category: 'backend', billingType: 'fixed_monthly',
      baseAmount: 25, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
      notes: '$25/month flat — DB, Auth, Storage, Realtime', enabled: true,
    },
    {
      id: 'demo-3', name: 'Supabase Storage Egress', serviceKey: 'supabase_storage_bandwidth',
      category: 'network', billingType: 'usage_per_user',
      baseAmount: 0, perUserAmount: 0, usagePerUser: 0.05, unitCost: 0.09, unitLabel: 'GB/month per user', seats: 1, amortizeMonths: 12,
      notes: '~50 MB egress per user/month · $0.09/GB after 5 GB free', enabled: true,
    },
    // ── Firebase usage (Blaze) ──
    {
      id: 'demo-4', name: 'Firebase Firestore Reads', serviceKey: 'firebase_firestore',
      category: 'backend', billingType: 'usage_per_user',
      baseAmount: 0, perUserAmount: 0, usagePerUser: 500, unitCost: 0.0000006, unitLabel: 'reads/month per user', seats: 1, amortizeMonths: 12,
      notes: '~500 doc reads/user/month · $0.06 per 100K reads', enabled: true,
    },
    {
      id: 'demo-5', name: 'Firebase Cloud Functions', serviceKey: 'firebase_functions',
      category: 'backend', billingType: 'usage_per_user',
      baseAmount: 0, perUserAmount: 0, usagePerUser: 10, unitCost: 0.0000004, unitLabel: 'invocations/month per user', seats: 1, amortizeMonths: 12,
      notes: '~10 function calls/user/month · $0.40/1M after 2M free', enabled: true,
    },
    // ── AI API ──
    {
      id: 'demo-6', name: 'OpenAI API (monthly budget)', serviceKey: null,
      category: 'ai', billingType: 'fixed_monthly',
      baseAmount: 2, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
      notes: 'Current ~$2/month spend — switch to usage_per_user once you know tokens/user', enabled: true,
    },
    // ── Infrastructure ──
    {
      id: 'demo-7', name: 'Hetzner CX32 (Backend Server)', serviceKey: 'hetzner_cx32',
      category: 'infrastructure', billingType: 'fixed_monthly',
      baseAmount: 8.90, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
      notes: '4 vCPU / 8 GB RAM — primary backend server', enabled: true,
    },
    // ── Mobile ──
    {
      id: 'demo-8', name: 'Apple App Store Developer', serviceKey: 'apple_app_store',
      category: 'mobile', billingType: 'fixed_annual',
      baseAmount: 99, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 12,
      notes: '$99/year → $8.25/month amortized', enabled: true,
    },
    {
      id: 'demo-9', name: 'Google Play Store Developer', serviceKey: 'google_play_store',
      category: 'mobile', billingType: 'one_time',
      baseAmount: 25, perUserAmount: 0, usagePerUser: 0, unitCost: 0, unitLabel: '', seats: 1, amortizeMonths: 36,
      notes: '$25 one-time → $0.69/month over 36 months', enabled: true,
    },
  ],
};
